# ============================================================================
# Supabase プロジェクト sato-class-data セットアップスクリプト (PowerShell)
# 参照: ~/.claude/projects/C--Users-K5610/memory/reference_supabase-cli-setup.md
# 前提: SUPABASE_ACCESS_TOKEN を環境変数に設定済み
# ============================================================================

param(
    [string]$ProjectName = "sato-class-data",
    [string]$Region = "ap-northeast-1"
)

$ErrorActionPreference = "Stop"

# 1. Token チェック
if (-not $env:SUPABASE_ACCESS_TOKEN) {
    Write-Host "❌ SUPABASE_ACCESS_TOKEN が未設定です。" -ForegroundColor Red
    Write-Host "https://supabase.com/dashboard/account/tokens で発行し、" -ForegroundColor Yellow
    Write-Host "`$env:SUPABASE_ACCESS_TOKEN = 'sbp_xxx' を実行してください。" -ForegroundColor Yellow
    exit 1
}

# 2. 組織ID取得
Write-Host "📋 組織ID取得中..." -ForegroundColor Cyan
$orgsRaw = npx supabase orgs list 2>&1 | Out-String
Write-Host $orgsRaw

# データ行（ヘッダ・区切り以外）からIDを抽出
$orgId = ($orgsRaw -split "`n" | Where-Object { $_ -match '^\s*\|\s*\S' -and $_ -notmatch 'NAME' -and $_ -notmatch '----' } | ForEach-Object {
    if ($_ -match '\|\s*([a-z0-9]{20})\s*\|') { $matches[1] }
} | Select-Object -First 1)

if (-not $orgId) {
    Write-Host "❌ 組織IDの取得に失敗しました。手動で確認してください。" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Org ID: $orgId" -ForegroundColor Green

# 3. DBパスワード生成
$DbPassword = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_})
Write-Host "🔐 DBパスワード生成完了" -ForegroundColor Green

# 4. プロジェクト作成
Write-Host "🚀 プロジェクト '$ProjectName' を作成中（数十秒かかります）..." -ForegroundColor Cyan
$createResult = npx supabase projects create $ProjectName `
    --org-id $orgId `
    --region $Region `
    --db-password $DbPassword 2>&1 | Out-String
Write-Host $createResult

# REFERENCE ID 抽出
$projectRef = ($createResult -split "`n" | ForEach-Object {
    if ($_ -match '([a-z]{20})\.supabase\.co') { $matches[1] }
} | Select-Object -First 1)

if (-not $projectRef) {
    Write-Host "❌ プロジェクト参照IDの取得に失敗しました。" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Project Ref: $projectRef" -ForegroundColor Green

# 5. プロビジョニング待機
Write-Host "⏳ プロビジョニング待機中（最大2分）..." -ForegroundColor Cyan
$maxWait = 24
for ($i = 0; $i -lt $maxWait; $i++) {
    Start-Sleep -Seconds 5
    $code = (Invoke-WebRequest -Uri "https://$projectRef.supabase.co/rest/v1/" -SkipHttpErrorCheck -Method Head).StatusCode
    if ($code -eq 401 -or $code -eq 200) {
        Write-Host "✅ DB起動確認 (HTTP $code)" -ForegroundColor Green
        break
    }
    Write-Host "   待機中... ($($i*5)秒経過, HTTP $code)"
}

# 6. ローカルプロジェクトとリンク
Push-Location $PSScriptRoot
try {
    Write-Host "🔗 ローカルとリンク中..." -ForegroundColor Cyan
    npx supabase link --project-ref $projectRef --password $DbPassword

    # 7. DDL 適用
    Write-Host "📝 マイグレーション適用中..." -ForegroundColor Cyan
    npx supabase db push --password $DbPassword --yes

    # 8. API Keys 取得
    Write-Host "🔑 API Keys 取得中..." -ForegroundColor Cyan
    $apiKeysRaw = npx supabase projects api-keys --project-ref $projectRef 2>&1 | Out-String
    Write-Host $apiKeysRaw
}
finally {
    Pop-Location
}

# 9. .env に書き出し
$envFile = Join-Path $PSScriptRoot ".env"
@"
# Generated by setup.ps1 at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
SUPABASE_PROJECT_REF=$projectRef
SUPABASE_DB_PASSWORD=$DbPassword
SUPABASE_URL=https://$projectRef.supabase.co
# anon_key と service_role_key は上記の出力からコピーして以下に貼り付けてください
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
"@ | Out-File -FilePath $envFile -Encoding UTF8

Write-Host ""
Write-Host "🎉 セットアップ完了！" -ForegroundColor Green
Write-Host "📄 .env を確認し、anon_key と service_role_key を貼り付けてください: $envFile" -ForegroundColor Yellow
Write-Host "🔓 SUPABASE_ACCESS_TOKEN は使い終わったら revoke 推奨: https://supabase.com/dashboard/account/tokens" -ForegroundColor Yellow
